use customer_behavior;

SELECT * FROM customer limit 20;

-- Q1.what is the total revenue generated by male vs. female customer?

select gender,SUM(purchase_amount) as revenue
from customer
group by gender;

-- Q2. Which customer used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from customer
where discount_applied = "Yes" and purchase_amount >= (select AVG(purchase_amount)from customer);

-- Q3. which are the top 5 products with the highest average review rating?

select item_purchased , AVG(review_rating) as "Average Product rating"
from customer
group by item_purchased
order by AVG(review_rating) desc limit 5;

-- Q4. compare the average purchase amount between standard and express shipping.

select shipping_type,AVG(purchase_amount) 
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5.Do subscribe customers spend more? compare average and total revenue etween subscribers and non-subscribers.

select subscription_status,
       COUNT(customer_id) as total_customers,
       AVG(purchase_amount) as avg_purchase_amount,
       SUM(purchase_amount) as total_revenue
from customer
group by subscription_status;

